### ISSUE TITLE
Synthetic default imports

### ISSUE THREAD

**Issue by budnix** [handsontable/react-handsontable#116]
### Description

While testing `@handsontable/react` component using TypeScript I've spotted a compiling error caused by default import (`import React from 'react'` within the component). 

To make this work right now it's necessary to put `"allowSyntheticDefaultImports": true,` key to `tsconfig.json` file. This resolves the issue by making non-default importable modules to default one.

### Steps to reproduce

1. Create an app `create-react-app my-app --scripts-version=react-scripts-ts`;
2. Install Handsontable with simplified example and try to compile `yarn start`.
3. An error `Module '"/Users/budnix/test/my-app/node_modules/@types/react/index"' has no default export.` occurs.

### Your environment
* React wrapper version: 2.0.0
* Handsontable version: 6.2.0
* Browser Name and version: any
* Operating System: any

**Comment by wojciechczerniak** [comment]
Which version of `create-react-app` do you have? 

Since [`2.1.1`](https://github.com/facebook/create-react-app/releases/tag/v2.1.1) there is an option to use `--typescript` template. The project initialized with `2.1.1` has `tsconfig.json` where `allowSyntheticDefaultImports` is set to `true` by default.

Which is ["highly recommend applying it both to new and existing projects"](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop) since Typescript 2.7 (January 2018). We've took the more modern and future proof approach. At least until both React and Handsontable are updated with correct ES module exports.

**Comment by budnix** [comment]
Confirm, using `create-react-app my-app --typescript` for generating boilerplate adds  `allowSyntheticDefaultImports: true` by default. The issue can be closed.
