### ISSUE TITLE
TypeScript error: 'HotTable' refers to a value, but is being used as a type here.

### ISSUE THREAD

**Issue by pnowak** [handsontable/react-handsontable#178]
### Description
If we create react app with typescript and make use of our wrapper and typed `hotRef: React.RefObject<HotTable>` we receive an error `'HotTable' refers to a value, but is being used as a type here.`.

But we can't use `typeof operator` and try `hotRef: React.RefObject<typeof HotTable>;` because we get another error in `this.hotTableComponent.current.hotInstance` the `Property 'hotInstance' does not exist on type 'typeof HotTable'.`.

So it needs further investigation.

### Steps to reproduce

1. `create-react-app` and `npm install handsontable @handsontable/react` 
2. try to use type or interface and use refs
3. `npm run start`

### Demo

https://codesandbox.io/s/typescript-error-hottable-refers-to-a-value-but-is-being-used-as-a-type-here-xee4r?file=/src/index.tsx

### Your environment
* React wrapper version: 3.1.2
* Handsontable version: 7.4.2

**Comment by pnowak** [comment]
I researched the subject further and I think, however, it is not a bug. 

Some constructs, such as `class`, introduce both a TypeScript type and a value. In our context, 'HotTable' refers to value but is being used as a type here. To use it as a type we could try `typeof` operator. But  `typeof` on a `class` depends on the context. In our context (value) `typeof HotTable` result a `function`, because of how classes are implemented in JavaScript. In type context `typeof HotTable` is type `typeof HotTable`, not `HotTable` itself.
To use `HotTable` as a type we must use `InstanceType` generic `<InstanceType<typeof HotTable>>`. In that `HotTable` is a type.

Here is an updated demo - https://codesandbox.io/s/instancetype-typeof-oj6gu?file=/src/index.tsx

What do you think @jansiegel?

**Comment by jansiegel** [comment]
@pnowak This is really insightful, and most importantly - it seems to work fine! I think it's a good way to ensure we're getting what we want in terms of class typing.

This issue seems to be caused by the usage of the `addUnsafePrefixes` method, which takes a class, checks the React version, and prepends the `componentWillUpdate` and `componentWillMount` methods with the `UNSAFE_` prefix. I'm not sure why exactly this happens, but to be on the safe side, I moved the prefixing mechanism to the class constructor, so the typings for `HotTable` and `HotColumn` would remain unchanged on export. This way it should be possible to use `HotTable` as it was up to version `3.0.0`.

That being said, we should schedule a task to rewrite the wrapper logic to the new React architecture, so there's no need to prefix anything no more.

**Comment by aninde** [comment]
I have a problem verifying that the new version of `React-Handsontable` fixes this problem. @wojciechczerniak  tested this locally in his application and didn't notice the blocker for release.

**Comment by aninde** [comment]
The error was visible in the IDE. It is no longer present in the latest `Hot-React version 3.1.3`
![TSError](https://user-images.githubusercontent.com/30186818/79343620-e545c700-7f2e-11ea-8507-3fe064dfa776.gif)
