### ISSUE TITLE
Backspace in filter by value option does not work initially

### ISSUE THREAD

**Issue by RanaOsamaAwadallah** [handsontable/react-handsontable#181]
### Description
Backspace in filter by value option does not work initially. However if you focus out then focus in again it works.

### Steps to reproduce
1. Enable filters and dropdown
2. Try searching by value (type any value)
3. Delete (backspace)

### Demo
https://codesandbox.io/s/declaring-column-settings-1u5ew?file=/src/index.js

### Your environment
* React wrapper version: 3.1.3
* Handsontable version: 8.0.0-beta.1
* Browser Name and version: Chrome 81.0.4044.122 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing @RanaOsamaAwadallah 

I have replicated the same using simplified demo https://codesandbox.io/s/declaring-column-settings-plfc7 on Chrome 83 on Windows 10 and macOS Catalina.

The issue does not happen for [Vanilla](https://jsfiddle.net/AMBudnik/cL6amg8b/), [Angular](https://jsfiddle.net/AMBudnik/6ju0bpdg/), nor [Vue](https://jsfiddle.net/AMBudnik/xv4azebq/).

The demo loads Handsontable `8.0.0-beta1` but it works well in `7.4.2` https://codesandbox.io/s/declaring-column-settings-jee5e

**Comment by AMBudnik** [comment]
Issue moved to [handsontable/handsontable #6842](https://github.com/handsontable/handsontable/issues/6842) via [**ZenHub**](https://www.zenhub.com/)

**Comment by AMBudnik** [comment]
Hi @RanaOsamaAwadallah 

I’m glad to announce that Handsontable v8.0.0 that solves this issue is live!   You can use it by updating your Handsontable for React to v 4.0.0.

Release Notes for Handsontable for React v4.0.0 https://github.com/handsontable/react-handsontable/releases/tag/4.0.0
Release Notes for Handsontable v8.0.0 https://github.com/handsontable/handsontable/releases/tag/8.0.0

I highly encourage you to test the new version and leave some feedback.
