### ISSUE TITLE
Update to support v8.0.0

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/react-handsontable#189]
### Description

We need to check new breaking changes with the wrapper and update if needed.

**Comment by underfisk** [comment]
I have noticed there is a lack of unit tests for React wrapper, is there any upcoming considering on adding them?
Also, the wrapper lacks some performance optimizations such as **Memoization** 
Any date for echo renderers feature coming as a testing feature for react wrapper?

**Comment by AMBudnik** [comment]
@underfisk the eco-renderers project is on hold. We need to publish v8.0.0 and then we will be able to schedule further development.

> I have noticed there is a lack of unit tests for React wrapper

are you see any particular elements that are lacking the tests? I guess that it would be wise to provide missing scenarios.

**Comment by wojciechczerniak** [comment]
Can you please move the off-topic discussion to support@handsontable.com? Thank you.

**Comment by underfisk** [comment]
@AMBudnik Yes i'm aware but in React wrapper there are improvements that might be done, for example we end up using ReactDOM to append children into a TH/TD but React wrapper could accept a React.Node or JSX element and manage it by itself would be a good improvement and support
Regarding the tests, you can set up tests to test behavior such as re-rendering and memory usage (Since you are relying on an external module not created by React, it can interfere with Virtual DOM and there are no coverage to know whether it's optimized or not (even the wrapper itself can re-render multiple times, there is no Memoization)

**Comment by AMBudnik** [comment]
I know that we've discussed other topics in that issue but I just wanted to let you know that Handsontable for React v4.0.0 has just been released. It loads Handsontable 8.0.0 so it's definitely a version to check in your project.
Release notes for Handsontable v8 https://github.com/handsontable/handsontable/releases/tag/8.0.0
