### ISSUE TITLE
Rows misaligned with Header Row

### ISSUE THREAD

**Issue by ankitgoyal100** [handsontable/react-handsontable#206]
### Description
Rows are misaligned with the top header row (look at right side of table)
![Screen Shot 2020-11-23 at 2 22 40 PM](https://user-images.githubusercontent.com/3400675/100005749-73244300-2d97-11eb-8834-abd3c71b67de.png)

### Code
```
  const data = [
    ["", "Ford", "Volvo", "Toyota", "Honda"],
    ["2016", 10, 11, 12, 13],
    ["2017", 20, 11, 14, 13],
    ["2018", 30, 15, 12, 13]
  ];

  return <HotTable 
    data={data} 
    stretchH='all'
    colHeaders={true} 
    rowHeaders={true} 
    width="100%"
    height="auto"
    licenseKey='non-commercial-and-evaluation'
  />;
```

### Your environment
* React wrapper version: 4.0.0
* Handsontable version: 8.2.0

**Comment by AMBudnik** [comment]
Hi @ankitgoyal100 

this issue seems to be related to some CSS settings attached.

I've made an example using our wrapper and the latest version here https://jsfiddle.net/AMBudnik/9qdyj3zL/ 

![Zrzut ekranu 2020-11-24 o 09 53 51](https://user-images.githubusercontent.com/10757813/100071106-f9459580-2e3a-11eb-80cd-a997c32bc87b.png)

Can you extend my demo with your CSS settings?
