### ISSUE TITLE
Don't allow direct mutation of data prop

### ISSUE THREAD

**Issue by goodoldneon** [handsontable/react-handsontable#58]
HotTable directly mutates the array passed as the `data` prop. This is an anti-pattern and can cause issues.

```jsx
<HotTable
  settings={{
    data: this.state.data  // State is mutated... VERY BAD!!!!
  }}
/>
```

Shouldn't HotTable clone its `data` prop instead of directly mutating it? Users can do it manually on their own, but the clone should be implicit.

```jsx
<HotTable
  settings={{
    data: cloneDeep(this.state.data)  // State is not mutated... VERY GOOD!
  }}
/>
```

**Comment by AMBudnik** [comment]
Thank you for sharing the proposition @goodoldneon

**Comment by yinbinxu** [comment]
Hi @goodoldneon, I'm new to react and Javascript in general.  I'm working with HotTable as well.  So suppose HotTable clone a copy of the data, doesn't that mean you have to implement almost all the data event callbacks to propagate the data change to the data in your state?  Isn't that kind of defeating the purpose of using the HotTable component?  Would it be safe if in the parent component that uses HotTable ensure that the this.state.data is never modified by itself, it's only managed by the HotTable? Is there any "delegated state" concept in React with which the parent passes ownership to sub-components?

**Comment by goodoldneon** [comment]
@yinbinxu 

I'm not a React expert by any means, so I'm probably the wrong person to ask. That being said, let's say you have your data living in state in component `<Parent />`. You pass the data as props to child components `<HotTable />` and `<Stats />`. If `<HotTable />` is directly mutating the data, and the data is consequently not updating via `setState()`, then `<Stats />` will display outdated data.

In my opinion, the best way to handle this would be a prop function on `<HotTable />` which returns the updated data as a new object.

**Comment by iamgreyy** [comment]
Thank you man you`re made my day. I spent many time to understand what happens with my settings.

**Comment by wojciechczerniak** [comment]
> Now i want to ask developers.
> Why its not fixed yet?

@iamgreyy Because there is nothing to fix.

That's how Javascript work and how React and Redux have to work. It's even written in their documentation and every blog post about React/Redux: you need to break references to the state if your're going to modify it. If Handsontable is used for read only, you don't have to do it. If it's an editor then you can. How you're going to do it is totally up to you and depends on the use case.

Creating deep copy of the data each time it changes doesn't make sense in most use cases. As @goodoldneon mentions it's very inefficient. Mostly related to the state, not always needed, it's not up to us to decide for developer where such optimization is necessary. Few would benefit from this, the reset would suffer. That's why it shouldn't be implicit and would have negative impact on performance.
