### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by byte9527** [handsontable/react-handsontable#97]
when I compile my project, there is a error 
![image](https://user-images.githubusercontent.com/30108509/44009648-e260df92-9edf-11e8-837a-53d1280fa7c1.png)

**Comment by wojciechczerniak** [comment]
Hi @byte9527. Looks like your build pipeline has a problem with one of Handsontable helpers during the minification stage. This is not an issue with this wrapper, maybe with Handsontable. But we don't have enough information about your build process and tools you use. Please provide a minimal demo so we can reproduce the issue. Otherwise, I'm afraid we won't be able to help you.
