### ISSUE TITLE
With a blank create-react-app handsontable has huge size

### ISSUE THREAD

**Issue by jandom** [handsontable/react-handsontable#99]
### Description

Installed handsontable with create-react-app. I was doing this investigating a rather large build sizes/slow build times in another code base. It seem that including react handsontable brings A LOT of weight into the project, parsed size is over 0.5 MB. 

Is that intentional, or am I importing something wrong?

### Steps to reproduce
```
$ npx create-react-app my-app-with-handsontable

$ cd my-app-with-handsontable

$ yarn eject

$ yarn install
```

This allows us to build a blank, ejected create-react-app

```
$ yarn build
yarn run v1.9.4
$ node scripts/build.js
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  36.94 KB  build/static/js/main.e8369a05.js
  299 B     build/static/css/main.c17080f1.css
[...]
✨  Done in 6.63s.
```

Then we install `webpack-bundle-analyzer` to understand the build size 

```
yarn add -D webpack-bundle-analyzer
```

Following instructions from https://docs.handsontable.com/5.0.1/frameworks-wrapper-for-react-installation.html?_ga=2.264884364.2073251238.1534509989-2097387745.1526563895
I installed handsontable and included it in App.js

```
yarn add handsontable @handsontable/react
```

Here we can build again, 

```
$ yarn build 
yarn run v1.9.4
$ node scripts/build.js
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  227.63 KB (+190.68 KB)  build/static/js/main.8c43a8b9.js
  299 B                   build/static/css/main.c17080f1.css
[...]
```

Build size increases 6-fold, here is what webpack-bundle-analyzer shows

![screen shot 2018-08-17 at 1 48 07 pm](https://user-images.githubusercontent.com/395931/44267160-12efdf80-a225-11e8-9a26-d4465433b360.png)

Handsontable is much bigger than everything else combined, and by a thick margin. Am I doing something wrong including it, or is it just a beast in terms of size?

I'm leaving aside the question of why moment.js is included twice, that's a separate problem...

**Comment by wojciechczerniak** [comment]
Looks right. 1.7Mb is the size of main [`handsontable.js`](https://github.com/handsontable/handsontable/blob/master/dist/handsontable.js) build without dependencies. File is that big because it contains comments and JSDocs. Should be around [620Kb](https://github.com/handsontable/handsontable/blob/master/dist/handsontable.min.js) after minify/uglify that and even less after it's gzipped.

The file contains everything Handsontable has to offer and that's a long list. We're considering an alternative approach to the build process so everyone can optimize their app size: https://github.com/handsontable/handsontable/issues/5095 (the multi-part library point). Currently such optimizations are possible with [hot-builder](https://github.com/handsontable/hot-builder).
